/* 中文高保真原型。无真实录音、网络识别或文件上传。 */
const icons={
  back:'<path d="m15 5-7 7 7 7"/>',chevron:'<path d="m9 5 7 7-7 7"/>',
  plus:'<path d="M12 5v14M5 12h14"/>',calendar:'<rect x="3" y="5" width="18" height="16" rx="3"/><path d="M7 3v4M17 3v4M3 10h18M8 14h2M14 14h2M8 17h2"/>',
  book:'<path d="M12 5v15M3 4c4-1 6-1 9 1 3-2 5-2 9-1v15c-4-1-6-1-9 1-3-2-5-2-9-1Z"/>',
  plan:'<rect x="4" y="3" width="16" height="18" rx="3"/><path d="m8 8 1 1 2-2M13 8h3m-8 5 1 1 2-2M13 13h3M8 18h8"/>',
  user:'<circle cx="12" cy="8" r="4"/><path d="M5 21v-2a7 7 0 0 1 14 0v2"/>',
  search:'<circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/>',
  mic:'<rect x="9" y="2" width="6" height="13" rx="3"/><path d="M5 10v2a7 7 0 0 0 14 0v-2M12 19v3M8 22h8"/>',
  check:'<path d="m5 12 4 4L19 6"/>',checkCircle:'<circle cx="12" cy="12" r="9"/><path d="m7 12 3 3 7-7"/>',
  repeat:'<path d="m17 2 4 4-4 4M3 11V9a3 3 0 0 1 3-3h15M7 22l-4-4 4-4M21 13v2a3 3 0 0 1-3 3H3"/>',
  play:'<path d="m8 4 12 8-12 8Z"/>',pause:'<path d="M8 5v14M16 5v14"/>',stop:'<rect x="6" y="6" width="12" height="12" rx="2"/>',
  volume:'<path d="m12 3-6 5H2v8h4l6 5ZM16 8a6 6 0 0 1 0 8M19 5a10 10 0 0 1 0 14"/>',
  eye:'<path d="M2 12s4-7 10-7 10 7 10 7-4 7-10 7S2 12 2 12Z"/><circle cx="12" cy="12" r="3"/>',
  text:'<path d="M4 5h16M12 5v15M8 20h8"/>',shield:'<path d="m12 2 9 4v6c0 5-9 10-9 10S3 17 3 12V6Z"/><path d="m8 11 3 3 5-5"/>',
  clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',alert:'<path d="m12 3 10 18H2Z"/><path d="M12 9v5M12 17h.01"/>',
  file:'<path d="M14 2H5a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V9Z"/><path d="M14 2v7h7M7 13h10M7 17h7"/>',
  settings:'<path d="M4 7h16M4 17h16"/><circle cx="9" cy="7" r="3" fill="white"/><circle cx="15" cy="17" r="3" fill="white"/>',
  signal:'<path d="M3 13v3M7 10v6M11 6v10M15 3v13"/>',wifi:'<path d="M2 8a16 16 0 0 1 20 0M5 12a11 11 0 0 1 14 0M9 16a5 5 0 0 1 6 0M12 19h.01"/>',
  battery:'<rect x="1" y="6" width="18" height="12" rx="3"/><path d="M22 10v4M5 10h10v4H5Z" fill="currentColor" stroke="none"/>',
  keyboard:'<rect x="2" y="5" width="20" height="14" rx="3"/><path d="M6 9h.01M10 9h.01M14 9h.01M18 9h.01M6 12h.01M10 12h.01M14 12h.01M18 12h.01M7 16h10"/>'
};
const icon=(name,cls='')=>`<svg class="${cls}" viewBox="0 0 24 24" aria-hidden="true">${icons[name]||icons.file}</svg>`;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const target='积土成山，风雨兴焉；积水成渊，蛟龙生焉；积善成德，而神明自得，圣心备焉。';
const sampleArticle='君子曰：学不可以已。青，取之于蓝，而青于蓝；冰，水为之，而寒于水。\n\n吾尝终日而思矣，不如须臾之所学也；吾尝跂而望矣，不如登高之博见也。\n\n'+target;
const normalize=s=>s.replace(/[\p{P}\p{Z}\s]/gu,'');
function align(expected,spoken){
  const a=Array.from(normalize(expected)),b=Array.from(normalize(spoken));
  const dp=Array.from({length:a.length+1},()=>Array(b.length+1).fill(0));
  for(let i=0;i<=a.length;i++)dp[i][0]=i;
  for(let j=0;j<=b.length;j++)dp[0][j]=j;
  for(let i=1;i<=a.length;i++)for(let j=1;j<=b.length;j++)dp[i][j]=Math.min(dp[i-1][j]+1,dp[i][j-1]+1,dp[i-1][j-1]+(a[i-1]===b[j-1]?0:1));
  let i=a.length,j=b.length,deleted=0,substituted=0,inserted=0;
  while(i||j){
    if(i&&j&&dp[i][j]===dp[i-1][j-1]+(a[i-1]===b[j-1]?0:1)){if(a[i-1]!==b[j-1])substituted++;i--;j--;}
    else if(i&&dp[i][j]===dp[i-1][j]+1){deleted++;i--;}
    else{inserted++;j--;}
  }
  return {accuracy:a.length?Math.max(0,1-(deleted+substituted+inserted)/a.length)*100:0,coverage:a.length?(a.length-deleted)/a.length*100:0,deleted,substituted,inserted,total:a.length};
}
const fixtures={pass:target.replace('而神明','神明'),fail:'积土成山，风雨兴焉；积水成渊，蛟龙生焉。',uncertain:target.replace('蛟龙','交通')};
const state={screen:'today',importText:sampleArticle,importTitle:'劝学（节选）',segments:sampleArticle.split(/\n\s*\n/),filter:'全部',mask:false,large:false,paused:false,recordOutcome:'pass',accuracy:90,coverage:95,ruleDraft:{accuracy:90,coverage:95},taskDone:false,transcript:false,assisted:false,planStart:'2026-10-08',planEnd:'2026-10-31',quota:1,weekdays:[1,2,3,4,5,6,0],planArticles:['劝学','师说'],planName:'十月古文计划',planSaved:false,hasImported:false,reviewDecision:null,finalizing:false,lastResult:'pass',libraryQuery:'',signedIn:false,audioBackup:false,lastBackup:false};
const screens=[
 ['today','今日','任务入口'],['library','文库','文章管理'],['import','导入文字','粘贴正文'],['segments','确认分段','可编辑段落'],
 ['planform','新建计划','配额与截止日'],['planview','计划详情','排期与进度'],['read','阅读练习','原文与辅助'],['record','语音考核','无提示背诵'],
 ['result','达标校对','自动完成任务'],['review','识别待确认','回听复核'],['profile','我的','学习记录'],['settings','考核规则','透明判定'],
 ['failure','未达标校对','薄弱句重练'],['empty','文库空状态','首次使用'],['typing','文字考核','输入后校对'],['micerror','录音不可用','恢复路径'],['account','账户与数据','本机档案'],['backup','备份与同步','换机恢复'],['signin','登录账户','按需登录'],['weekly','学习周报','本周重点'],['monthly','学习月报','月度目标'],['yearly','学习年报','长期积累']
];
const notes={
 account:['账户可选','不登录也可完整学习，本机保存内容与记录。首次登录预览本机档案与云端档案再合并，不覆盖历史。演示登录不连接任何账户服务。'],
 backup:['备份不等于同步','同步用于多设备增量合并，版本备份用于恢复误删。默认不同步音频；清理音频不删除成绩。原型只切换演示状态。'],
 signin:['在需要时登录','换机或同步时再登录，默认提供 Apple 登录；正式产品展示服务条款及隐私说明。原型没有真实登录或外部链接。'],
 weekly:['周报指导下一周','完成率只统计本周已到期的必做任务；复习保持率来自实际复习考核。点击薄弱段落可以去练习。样例为上一完整周。'],
 monthly:['月报看目标与掌握','按计划说明文章目标是否达到，再看新掌握小节与复习表现。历史月份固定数据版本，迟到同步时标记更新。'],
 yearly:['年报看长期积累','统计按文章版本去重的掌握内容，月度分布展示学习持续性。全年不足一年也可查看阶段报告，缺数据不估算遗忘曲线。'],
 today:['任务入口','每次打开先回答“今天背什么”。新背、复习与完成状态在同一队列。单段通过只完成对应任务，全部必做任务完成后才形成当天打卡。'],
 library:['内容是核心','文库保存文章与有顺序的段落。全文修改生成新版本，旧成绩保留旧原文，不因重新分段而丢失历史。'],
 import:['先确认原文','默认按空行拆分，导入后先预览。首版支持粘贴及文本文件；OCR、PDF等解析能力后续接入。演示中的文件入口不访问用户文件。'],
 segments:['分段可调整','点击合并能实际改变节数，编辑可修改文本，保存后返回文库。正式App补齐拖拽和手动句边界。段落身份独立于节序。'],
 planform:['排期可计算','学习日、日期与配额会实时影响预览。容量不足时禁止创建，并提示调整每日节数或截止日期。新背与复习独立排期。'],
 planview:['剩余量可见','进度展示段落数，月份标注任务日。漏背后预览顺延或重排，不静默修改历史打卡。'],
 read:['练习与考核分开','阅读、遮字、首字与朗读都属于练习。开始考核会开一个新会话，隐藏原文；练习不能生成自动通过。'],
 record:['最终结果才评分','这是模拟录音页面，不采集声音。演示可选择达标、漏整句或识别疑点。真实接入先等待最终识别结果，再校对；暂不把临时转录计入成绩。'],
 result:['规则全部满足','达标样例仅漏“而”，内容一致率与覆盖率为28/29。正式业务在最终判定后自动记账，点击返回无需重复打卡。'],
 review:['识别疑点不是背错','原文“蛟龙”被识别成“交通”时，回听音频再判断。人工确认保留独立来源，不能把修订文字伪装成自动考核。'],
 profile:['记录要分来源','统计区分自动通过、人工确认和有辅助练习。录音可清理，历史分数和对应原文版本保留。'],
 settings:['规则可解释','阈值按原始精度判定，不能因显示四舍五入而通过。新规则只作用于后续会话，历史成绩保留规则快照。'],
 failure:['有明确恢复路径','未达标样例漏最后一句，覆盖16/29。先练薄弱句，再完整重考；不能把多次最好片段拼成整节通过。'],
 empty:['首用即能行动','空文库只引导导入第一篇，不放假文章。'],
 typing:['与语音共用校对','原文隐藏，文字输入后使用同一套内容规则。演示按钮用于填入样本文字，真实产品不提供此按钮。'],
 micerror:['技术故障不扣成绩','权限拒绝、语种不支持和识别失败都不给“背诵失败”。提供恢复设置、重试与文字考核。']
};
const tabs=active=>`<nav class="bottom-tabs" aria-label="主导航">${[['today','calendar','今日'],['library','book','文库'],['planview','plan','计划'],['profile','user','我的']].map(([id,ico,label])=>`<button class="${active===id?'selected':''}" data-go="${id}" aria-current="${active===id?'page':'false'}">${icon(ico)}<span>${label}</span></button>`).join('')}</nav>`;
state.settingsBack='profile';
const navTop=(title,back='today',right='')=>`<header class="toolbar"><button class="back" data-go="${back}" aria-label="返回">${icon('back')}返回</button><strong>${title}</strong>${right?`<button class="right" data-action="${right}">保存</button>`:'<span class="right" aria-hidden="true"></span>'}</header>`;
const heading=(title,subtitle='',action='')=>`<header class="large-header"><div class="header-row"><h1>${title}</h1>${action?`<button aria-label="${action==='import'?'导入文章':'新建计划'}" data-go="${action}">${icon('plus')}</button>`:''}</div>${subtitle?`<p class="subtitle">${subtitle}</p>`:''}</header>`;
const footer=(label,action,sub='',secondary='')=>`<footer class="bottom-action"><button class="primary" ${action.startsWith('go:')?`data-go="${action.slice(3)}"`:`data-action="${action}"`}>${label}</button>${sub?`<p class="small">${sub}</p>`:''}${secondary}</footer>`;
const row=(ico,title,meta,to,badge='',green=false)=>`<button class="list-row" data-go="${to}"><span class="row-icon ${green?'green':''}">${icon(ico)}</span><span class="row-content"><h3>${title}</h3><p>${meta}</p></span>${badge}${icon('chevron','row-chevron')}</button>`;
const sw=(on,action,label)=>`<button class="switch ${on?'on':''}" data-action="${action}" role="switch" aria-checked="${on}" aria-label="${label}"></button>`;
function today(){const done=state.taskDone?2:1;return heading('今日','10月8日 星期四')+`<div class="scroll-body"><section class="section panel tint"><div class="horizontal"><div><p class="small blue">今日任务</p><div class="summary-number numeric">${done}<small> / 3 已完成</small></div></div><div style="text-align:right"><p class="label">预计 ${state.taskDone?'4':'10'} 分钟</p><p class="small muted" style="margin-top:6px">新背 1 节 · 复习 2 节</p></div></div><div class="progress"><span style="width:${done/3*100}%"></span></div></section><section class="section"><div class="section-heading"><h2>接下来</h2><span class="small muted">十月古文计划</span></div><div class="list">${state.taskDone?row('checkCircle','劝学 · 第3节','内容一致率 96.6% · 已自动通过','result','<span class="badge green">已完成</span>',true):row('book','劝学 · 第3节','新背 · 积土成山 · 约6分钟','read','<span class="badge">新背</span>')}${row('repeat','劝学 · 第2节','今日到期 · 上次通过 94.2%','read','<span class="badge">复习</span>')}${row('checkCircle','劝学 · 第1节','今日 08:12 · 自动考核通过','result','',true)}</div></section><section class="section"><div class="section-heading"><h2>本月目标</h2><button data-go="planview">查看计划</button></div><div class="horizontal"><div><h3>背完 2 篇古文</h3><p class="small muted" style="margin-top:6px">${state.taskDone?'3':'2'} / 12 节已通过 · 10月31日截止</p></div><span class="large-text numeric">${state.taskDone?'25':'17'}<small style="font-size:16px">%</small></span></div></section></div>`+footer(state.taskDone?'继续今日复习':'开始今日背诵','go:read')+tabs('today');}
function library(){return heading('文库','把想记住的文字，放在这里','import')+`<div class="scroll-body"><div class="searchbox">${icon('search')}<input id="library-search" aria-label="搜索文章" placeholder="搜索文章或作者" value="${esc(state.libraryQuery)}"></div><div class="segmented library-filters">${['全部','背诵中','已完成'].map(x=>`<button data-filter="${x}" class="${state.filter===x?'selected':''}">${x}</button>`).join('')}</div><div id="library-list">${libraryRows()}</div><div class="info-strip" style="margin-top:24px">先保存原文与段落，再把文章加入计划。<br>每一节都可以单独练习、考核和复习。</div></div>`+tabs('library');}
function libraryRows(){if(state.filter==='已完成')return `<div class="empty-state" style="min-height:280px"><h2>还没有完成的文章</h2><p>整篇段落通过后，会显示在这里。</p></div>`;const all=[['劝学（节选）',`荀子 · ${state.hasImported?state.segments.length:6}节 · ${state.taskDone?3:2}节已通过`],['师说（节选）','韩愈 · 6节 · 尚未开始']].filter(x=>x[0].includes(state.libraryQuery));return all.length?all.map(([title,meta])=>row('file',title,meta,'read','<span class="badge">古文</span>')).join(''):`<div class="empty-state" style="min-height:280px"><h2>没有找到相关文章</h2><p>试试其他关键词。</p></div>`;}
function importScreen(){return navTop('导入文字','library')+`<div class="scroll-body" style="padding-top:18px"><p class="title-kicker">第1步 · 准备原文</p><h2 style="margin-bottom:20px">添加一篇文章</h2><div class="segmented"><button class="selected">粘贴文字</button><button data-action="file-demo">导入文件</button></div><div class="field"><label for="article-title">文章标题</label><input id="article-title" value="${esc(state.importTitle)}" placeholder="例如：劝学（节选）"></div><div class="field"><label for="article-text">正文</label><textarea id="article-text" aria-label="文章正文">${esc(state.importText)}</textarea><p class="small">建议段落之间空一行，方便自动分段。</p></div><div class="horizontal"><span class="small muted" id="import-count">${normalize(state.importText).length} 字</span><button class="text-button" style="width:auto" data-action="clear-import">清空正文</button></div></div>`+footer('预览分段','preview-segments','先确认分段，再保存到文库');}
function segmentScreen(){return navTop('确认分段','import')+`<div class="scroll-body" style="padding-top:18px"><div class="horizontal" style="margin-bottom:12px"><div><h2>${esc(state.importTitle)}</h2><p class="small muted" style="margin-top:7px">按空行拆分 · 共 ${state.segments.length} 节</p></div><button class="text-button" style="width:auto" data-action="split-sentences">按句拆分</button></div><div class="info-strip">每节可调整内容。合并或拆分后，确认原文没有遗漏。</div>${state.segments.map((s,i)=>`<article class="paragraph-item"><div class="item-heading"><span class="count-pill">${i+1}</span><h3>第${i+1}节</h3><span class="small">${normalize(s).length}字</span></div><p>${esc(s)}</p><div class="paragraph-actions"><button data-edit-segment="${i}">编辑</button>${i<state.segments.length-1?`<button data-merge="${i}">与下一节合并</button>`:''}</div></article>`).join('')}</div>`+footer('保存文章','save-article','段落顺序将用于背诵排期');}
function planPreview(){const selected=state.planArticles.length*6,n=state.hasImported&&state.planArticles.length===1?state.segments.length:selected;const start=new Date(state.planStart+'T12:00:00'),end=new Date(state.planEnd+'T12:00:00');let dates=[];if(!Number.isNaN(+start)&&!Number.isNaN(+end)&&start<=end&&state.weekdays.length&&state.quota>=1){for(let d=new Date(start),guard=0;d<=end&&guard<370;d.setDate(d.getDate()+1),guard++)if(state.weekdays.includes(d.getDay()))dates.push(new Date(d));}const need=Math.ceil(n/state.quota),fits=n>0&&need<=dates.length;const finish=fits?dates[need-1]:null;const fmt=d=>`${d.getMonth()+1}月${d.getDate()}日`;return {n,need,days:dates.length,fits,finish,finishText:finish?fmt(finish):'无法在截止日前完成',spare:Math.max(0,dates.length-need),dates};}
function planform(){const p=planPreview();return navTop('新建计划','planview')+`<div class="scroll-body" style="padding-top:18px"><p class="title-kicker">把月度目标，变成每天的一小节</p><div class="field" style="margin-top:14px"><label for="plan-title">计划名称</label><input id="plan-title" value="${esc(state.planName)}"></div><div class="section" style="margin-bottom:18px"><div class="section-heading" style="margin-bottom:5px"><h2 style="font-size:16px">选择文章</h2><span class="small muted">${p.n} 节待安排</span></div><div class="form-list">${['劝学','师说'].map(a=>`<label class="form-row" style="cursor:pointer"><span>${a}（节选） <span class="small muted">6节</span></span><input type="checkbox" data-article="${a}" ${state.planArticles.includes(a)?'checked':''} aria-label="选择${a}" style="accent-color:var(--accent);width:19px;height:19px"></label>`).join('')}</div></div><div class="field-row"><div class="field"><label for="plan-start">开始日期</label><input id="plan-start" type="date" value="${state.planStart}"></div><div class="field"><label for="plan-end">截止日期</label><input id="plan-end" type="date" value="${state.planEnd}"></div></div><div class="form-list"><div class="form-row"><span>每天新背</span><span class="rules-input"><input id="plan-quota" type="number" min="1" max="10" value="${state.quota}" aria-label="每天新背节数"><span style="font-size:14px">节</span></span></div></div><div class="week" aria-label="学习日">${[[1,'一'],[2,'二'],[3,'三'],[4,'四'],[5,'五'],[6,'六'],[0,'日']].map(([d,l])=>`<button data-weekday="${d}" class="${state.weekdays.includes(d)?'selected':''}" aria-pressed="${state.weekdays.includes(d)}" aria-label="周${l}学习">${l}</button>`).join('')}</div><div id="plan-preview" class="panel ${p.fits?'tint':'warning'}"><p class="label ${p.fits?'blue':'orange'}">${p.fits?`预计 ${p.finishText} 完成新背`:'当前安排无法完成目标'}</p><p class="small muted" style="margin-top:7px">${p.fits?`${p.n}节 · ${p.need}个新背日 · 剩余${p.spare}天巩固`:'请增加每日节数、延长日期或减少文章。'}</p></div><div class="form-row"><span>每日提醒</span><span class="value">20:30</span></div><div class="form-row"><span>通过条件</span><button data-go="settings">${state.accuracy}%一致率 ${icon('chevron')}</button></div></div>`+`<footer class="bottom-action"><button class="primary" data-action="create-plan" ${p.fits?'':'disabled'}>创建计划</button><p class="small">复习任务会额外安排，不占用新背节数。</p></footer>`;}
function calendar(){return `<div class="calendar">${['一','二','三','四','五','六','日'].map(x=>`<div class="weekday">${x}</div>`).join('')}${Array(3).fill('<div></div>').join('')}${Array.from({length:31},(_,i)=>`<div class="day ${i+1===8?'today':i<2?'done planned':i<19?'planned':''}">${i+1}</div>`).join('')}</div>`;}
function planview(){const n=planPreview().n;const title=state.planName||'十月古文计划';const count=state.planArticles.length;const start=state.planStart.slice(5).replace('-','月')+'日';const end=state.planEnd.slice(5).replace('-','月')+'日';return heading('计划','每天一小节，按自己的节奏','planform')+`<div class="scroll-body"><div class="section"><div class="horizontal"><div><h2>${esc(title)}</h2><p class="small muted" style="margin-top:8px">${start}—${end} · ${count}篇 · ${n}节</p></div><span class="badge">${state.planSaved?'进行中':'草稿'}</span></div><div class="horizontal" style="margin-top:23px"><span class="summary-number numeric">${state.taskDone?3:2}<small> / ${n} 节</small></span><span class="small muted">已考核通过</span></div><div class="progress"><span style="width:${state.taskDone?25:17}%"></span></div></div><div class="section"><div class="section-heading"><h2>十月排期</h2><span class="small muted">蓝点：有任务</span></div>${calendar()}</div><div class="section"><div class="section-heading"><h2>今天 · 10月8日</h2><span class="small muted">1节新背，2节复习</span></div><div class="list">${row('book','劝学 · 第3节','积土成山 · 待考核','read')}${row('repeat','劝学 · 第2节','到期复习 · 约4分钟','read')}</div></div><div class="form-list"><div class="form-row"><span>调整剩余排期</span><button data-action="replan">调整 ${icon('chevron')}</button></div><div class="form-row"><span>考核规则</span><button data-go="settings">${state.accuracy}%一致率 ${icon('chevron')}</button></div></div></div>`+tabs('planview');}
function read(){let text=esc(target);if(state.mask)text=text.replace('风雨兴焉','<span class="mask">风雨兴焉</span>').replace('蛟龙生焉','<span class="mask">蛟龙生焉</span>').replace('圣心备焉','<span class="mask">圣心备焉</span>');return navTop('阅读练习','today')+`<div class="scroll-body"><div class="reading-title"><p class="title-kicker">劝学（节选） · 第3节 / 共6节</p><h2>积土成山</h2><p>荀子</p></div><div class="reading" ${state.large?'style="font-size:24px"':''}><p>${text}</p></div><div class="reading-toolbar"><button data-action="read-aloud">${icon('volume')}听原文</button><button data-action="toggle-mask">${icon('eye')}${state.mask?'显示原文':'遮字练习'}</button><button data-action="toggle-size">${icon('text')}调整字号</button></div><div style="border-top:1px solid var(--line);margin-top:14px;padding-top:22px"><h3>这一节的考核要求</h3><div class="checklist"><div>${icon('check')}内容一致率至少 ${state.accuracy}%</div><div>${icon('check')}原文覆盖率至少 ${state.coverage}%</div><div>${icon('check')}关键项：积善成德、圣心备焉</div></div><p class="small muted" style="line-height:1.7">练习时可以看提示。进入考核后会隐藏原文，达标即可完成这一节任务。</p></div></div>`+footer(`${icon('mic')}开始无提示考核`,'start-record','也可以用文字输入考核',`<button class="text-button" data-go="typing">切换文字考核</button>`);}
function record(){const heights=[8,12,20,13,31,45,29,15,33,52,39,24,47,58,36,20,46,31,17,41,52,30,14,26,37,17,11,22,14,8];return navTop('语音考核','read')+`<div class="scroll-body"><div class="record-title"><h2>劝学 · 第3节</h2><p>原文已隐藏，请完整背诵这一节</p></div><div class="record-indicator"><span class="dot"></span>${state.finalizing?'正在生成最终结果':state.paused?'已暂停':'正在聆听'}</div><div class="record-time">01:24</div><div class="waveform" aria-label="录音声音指示">${heights.map(h=>`<i style="height:${state.paused?5:h}px"></i>`).join('')}</div><button class="secondary-button" style="width:144px;margin:0 auto" data-action="pause">${icon(state.paused?'play':'pause')}${state.paused?'继续背诵':'暂停录音'}</button><div class="record-progress"><div class="horizontal"><span class="label">当前背诵进度</span><span class="label numeric blue">2 / 3 句</span></div><div class="progress"><span style="width:67%"></span></div><p class="small muted" style="margin-top:9px">进度为临时识别，最终结果仍会更新。</p></div><div class="inline-switch"><span>显示实时转录</span>${sw(state.transcript,'toggle-transcript','显示实时转录')}</div>${state.transcript?`<div class="info-strip" style="margin-top:12px">识别中：积土成山，风雨兴焉；积水成渊……<br>已切换为有辅助练习，本次不自动打卡。</div>`:''}<p class="record-tip">自然背诵，允许停顿。<br>结束后会对照原文校对漏句与错词。</p></div>`+footer(`${icon('stop')}${state.finalizing?'正在校对…':'结束并校对'}`,'finish-record',`通过条件：一致率 ${state.accuracy}% · 覆盖率 ${state.coverage}%`);}
function ruleRows(score,pass){return `<div class="rule-line"><span>原文覆盖率</span><span class="rule-value ${score.coverage>=state.coverage?'green':'red'}">${score.coverage.toFixed(1)}% ${icon(score.coverage>=state.coverage?'check':'alert')}</span></div><div class="rule-line"><span>关键项匹配</span><span class="rule-value ${pass?'green':'red'}">${pass?'2 / 2':'0 / 2'} ${icon(pass?'check':'alert')}</span></div><div class="rule-line"><span>考核状态</span><span class="rule-value ${pass?'green':'red'}">${pass?'无提示 · 完整考核':'存在整句遗漏'} ${icon(pass?'check':'alert')}</span></div>`;}
function result(failure=false){const score=align(target,fixtures[failure?'fail':'pass']);const meets=!failure&&score.accuracy>=state.accuracy&&score.coverage>=state.coverage;const automatic=meets&&!state.assisted;return navTop('校对结果','today')+`<div class="scroll-body"><div class="score-hero"><div class="status-title ${automatic?'green':state.assisted?'orange':'red'}">${icon(automatic?'checkCircle':'alert')}${automatic?'考核通过':state.assisted?'有辅助练习':failure?'仍需练习':'未达到当前规则'}</div><div class="score">${score.accuracy.toFixed(1)}<small>%</small></div><p class="score-caption">内容一致率 · 通过要求 ${state.accuracy}%</p></div><div class="panel ${automatic?'success':state.assisted?'warning':'white'}" style="padding:14px 16px;margin-bottom:22px">${ruleRows(score,!failure)}${automatic?`<p class="small green" style="border-top:1px solid #cce4d5;padding-top:12px;margin-top:7px">${icon('check').replace('<svg','<svg style="width:14px;height:14px;vertical-align:middle"')} 这一节任务已自动完成，下次复习：明天。</p>`:state.assisted?'<p class="small orange" style="padding-top:10px">本次使用了辅助提示，只记练习，不自动打卡。</p>':'<p class="small red" style="padding-top:10px">原文覆盖率或一致率不足，尚未完成任务。</p>'}</div><div class="section-heading"><h2>对照原文</h2><span class="small muted">${failure?'漏背1句':'漏背1字'}</span></div><div class="diff">积土成山，风雨兴焉；<br>积水成渊，蛟龙生焉；<br>${failure?'<span class="miss">积善成德，而神明自得，圣心备焉。</span>':'积善成德，<span class="miss">而</span>神明自得，圣心备焉。'}</div><div class="diff-legend"><span><i class="legend-dot"></i>红色下划线：漏背</span><span>标点不计分</span></div><div class="playback"><button aria-label="回听本次录音" data-action="play-demo">${icon('play')}</button><div class="track"><span></span></div><span class="small muted">01:24</span></div>${failure?'<p class="small muted">先练习漏背的最后一句，再完整考核这一节。</p>':'<p class="small muted">可以回听遗漏位置，帮助下次记得更完整。</p>'}</div>`+footer(automatic?'返回今日':failure?'练习薄弱句':'重新无提示考核',automatic?'complete-demo':failure?'go:read':'start-record','',failure?'<button class="text-button" data-action="start-record">直接重新考核</button>':'');}
function review(){return navTop('识别待确认','today')+`<div class="scroll-body" style="padding-top:20px"><div class="panel warning"><div class="horizontal" style="justify-content:flex-start;color:var(--warning);gap:8px">${icon('alert')}<h3>有 1 处识别疑点</h3></div><p class="small" style="color:var(--warning);margin-top:10px">可能是识别偏差，暂不判定背错。<br>确认前不会自动完成任务。</p></div><div class="section" style="margin-top:26px"><p class="title-kicker">劝学 · 第3节 · 第2句</p><h2>回听这一小段</h2><div class="review-pair"><div><p class="small muted">原文</p><p class="word">蛟龙</p></div>${icon('chevron')}<div class="uncertain"><p class="small orange">识别结果</p><p class="word orange">交通</p></div></div><p class="diff" style="font-size:18px">积水成渊，<span class="uncertain">交通</span>生焉。</p><div class="playback"><button aria-label="回听疑点音频" data-action="play-demo">${icon('play')}</button><div class="track"><span></span></div><span class="small muted">00:18—00:23</span></div><div class="form-list"><button class="form-row" style="width:100%;text-align:left" data-action="review-asr"><span>我说的是“蛟龙”</span><span class="value">识别错误</span></button><button class="form-row" style="width:100%;text-align:left" data-action="review-wrong"><span>这一处确实背错了</span><span class="value">转为练习</span></button></div>${state.reviewDecision?`<div class="info-strip" style="margin-top:14px">${state.reviewDecision==='asr'?'已记为人工确认，请重新考核以获得自动通过。':'已标记薄弱位置，建议回到练习。'}</div>`:''}</div><p class="small muted" style="line-height:1.8">人工确认会保留原始转录和录音。<br>不会把修订后的文字当成自动识别成绩。</p></div>`+footer('重新考核','start-record','这次任务仍待完成');}
function profile(){return heading('我的','记录每一次认真背诵')+`<div class="scroll-body"><section class="section"><div class="list">${row('user',state.signedIn?'我的账户':'本机学习档案',state.signedIn?'已登录 · 查看备份状态':'数据保存在此设备 · 可随时登录','account')}${row('plan','学习报告','周报 · 月报 · 年报','weekly')}</div></section><div class="section stat-grid"><div><p class="stat-number">${state.taskDone?3:2}<small> 节</small></p><p class="small">已考核通过</p></div><div><p class="stat-number">8<small> 次</small></p><p class="small">累计练习</p></div><div><p class="stat-number">42<small> 分钟</small></p><p class="small">专注时长</p></div><div><p class="stat-number">1<small> 个</small></p><p class="small">进行中的计划</p></div></div><section class="section"><div class="section-heading"><h2>最近记录</h2><span class="small muted">10月</span></div><div class="history-row"><div class="horizontal"><span>劝学 · 第1节</span><span class="green numeric">98.2%</span></div><p class="small">今天 08:12 · 自动通过 · 复习</p></div><div class="history-row"><div class="horizontal"><span>劝学 · 第2节</span><span class="blue numeric">94.2%</span></div><p class="small">10月2日 · 自动通过 · 新背</p></div><div class="history-row"><div class="horizontal"><span>劝学 · 第2节</span><span class="muted">有辅助练习</span></div><p class="small">10月2日 · 查看了首字提示</p></div></section><div class="form-list"><div class="form-row"><span>考核规则</span><button data-go="settings">${state.accuracy}%一致率 ${icon('chevron')}</button></div><div class="form-row"><span>语音与录音</span><button data-action="audio-settings">本地保存 ${icon('chevron')}</button></div><div class="form-row"><span>数据导出</span><button data-action="export-demo">导出 ${icon('chevron')}</button></div></div><p class="small muted" style="margin-top:18px;line-height:1.7">练习、自动通过、人工确认分别记录。<br>清理录音不会删除已保存的历史成绩。</p></div>`+tabs('profile');}
function settings(){return navTop('考核规则',state.settingsBack)+`<div class="scroll-body grouped"><div class="section"><p class="small muted" style="margin:0 4px 10px">通过阈值</p><div class="panel white" style="padding:0 16px"><div class="form-row"><span>内容一致率至少</span><label class="rules-input"><input id="rule-accuracy" type="number" value="${state.ruleDraft.accuracy}" min="50" max="100" aria-label="内容一致率阈值"><span>%</span></label></div><div class="form-row"><span>原文覆盖率至少</span><label class="rules-input"><input id="rule-coverage" type="number" value="${state.ruleDraft.coverage}" min="50" max="100" aria-label="原文覆盖率阈值"><span>%</span></label></div><div class="form-row"><span>关键项必须正确</span>${sw(true,'key-rule','关键项必须正确')}</div></div><p class="small muted" style="margin:10px 4px 0;line-height:1.7">一致率反映漏字、错词与多说；覆盖率反映是否背到了原文各部分。</p></div><div class="section"><p class="small muted" style="margin:0 4px 10px">语音容错</p><div class="panel white" style="padding:0 16px"><div class="form-row"><span>忽略标点与停顿</span>${sw(true,'normalization-rule','忽略标点与停顿')}</div><div class="form-row"><span>同音字辅助校准</span>${sw(true,'homophone-rule','同音字辅助校准')}</div><div class="form-row"><span>识别疑点先复核</span>${sw(true,'review-rule','识别疑点先复核')}</div></div><p class="small muted" style="margin:10px 4px 0;line-height:1.7">同音容错需有语音证据支持。数字与专名可标记为关键项。</p></div><div class="panel white"><div class="horizontal" style="justify-content:flex-start;gap:10px">${icon('shield')}<h3>无提示考核才自动打卡</h3></div><p class="small muted" style="margin-top:10px;line-height:1.8">查看原文、播放答案或使用首字提示，本次只记录练习。待确认的识别结果不自动通过。</p></div><p class="small muted" style="margin:16px 4px;line-height:1.8">新规则只作用于后续考核。<br>历史成绩保留当时使用的规则。</p></div>`+footer('保存规则','save-rules');}
function empty(){return heading('文库','从第一篇想记住的文章开始','import')+`<div class="scroll-body"><div class="empty-state"><span class="row-icon">${icon('book')}</span><h2>你的文库还是空的</h2><p>粘贴课文、古文或演讲稿，<br>拆成小节，安排每天的背诵。</p><button class="primary" data-go="import">${icon('plus')}导入第一篇</button></div></div>`+tabs('library');}
function typing(){return navTop('文字考核','read')+`<div class="scroll-body" style="padding-top:20px"><h2>劝学 · 第3节</h2><p class="small muted" style="margin-top:10px;line-height:1.8">原文已隐藏。按记忆输入完整内容，标点和换行不影响评分。</p><div class="field" style="margin-top:24px"><label for="typed-answer">我的背诵内容</label><textarea class="text-entry" id="typed-answer" placeholder="从这里开始默写……"></textarea></div><div class="info-strip">和语音考核使用相同的内容一致率、覆盖率与关键项规则。</div><div class="checklist"><div>${icon('check')}内容一致率至少 ${state.accuracy}%</div><div>${icon('check')}原文覆盖率至少 ${state.coverage}%</div><div>${icon('check')}无提示完整考核</div></div></div>`+footer('提交并校对','submit-typing');}
function micerror(){return navTop('语音考核','read')+`<div class="scroll-body"><div class="mic-unavailable"><span class="row-icon">${icon('mic')}</span><h2>暂时无法使用麦克风</h2><p>请允许麦克风和语音识别权限，<br>再回来开始背诵。</p><div class="panel"><h3>你可以这样继续</h3><div class="checklist"><div>${icon('check')}到系统设置中开启权限</div><div>${icon('check')}改用文字输入考核</div></div><p class="small muted">这次尚未开始考核，不会产生未达标记录。</p></div></div></div>`+footer('前往系统设置','system-settings','',`<button class="text-button" data-go="typing">改用文字考核</button>`);}

function account(){return navTop('账户与数据','profile')+`<div class="scroll-body" style="padding-top:24px"><section class="section"><div class="horizontal" style="justify-content:flex-start;gap:14px"><span class="row-icon">${icon('user')}</span><div><h2>${state.signedIn?'我的账户':'本机学习档案'}</h2><p class="small muted" style="margin-top:5px">${state.signedIn?'已登录 · 学习记录可跨设备恢复':'无需注册，也能完整使用'}</p></div></div></section><section class="section panel tint"><h3>每一次背诵，都有记录</h3><p class="small muted" style="margin-top:8px;line-height:1.8">文章、分段、计划和成绩保存在本机。${state.signedIn?'连接网络时同步，离线也能继续学习。':'登录后可备份，在新设备恢复学习进度。'}</p></section><section class="section"><div class="section-heading"><h2>已保存到本机</h2></div><div class="form-list"><div class="form-row"><span>文章与原文版本</span><span class="value">2篇 · 12节</span></div><div class="form-row"><span>背诵计划</span><span class="value">1个</span></div><div class="form-row"><span>考核与练习记录</span><span class="value">8次</span></div><div class="form-row"><span>录音</span><span class="value">仅本机 · 保留7天</span></div></div></section><div class="list">${row('repeat','备份与同步',state.signedIn?'查看同步状态与恢复点':'设置备份范围与恢复方式','backup')}${row('file','导出学习档案','可恢复的完整档案与可阅读的成绩表','backup')}</div><p class="small muted" style="margin-top:18px;line-height:1.8">本机数据不会因退出账户自动清除。<br>切换账户前先选择要保留的档案。</p></div>`+footer(state.signedIn?'查看备份状态':'登录并保留进度',state.signedIn?'go:backup':'go:signin');}
function backup(){return navTop('备份与同步','account')+`<div class="scroll-body grouped" style="padding-top:20px"><section class="section panel white"><div class="horizontal"><h3>${state.signedIn?'同步已开启':'本机数据已保存'}</h3><span class="badge ${state.signedIn?'green':''}">${state.signedIn?'已登录':'未登录'}</span></div><p class="small muted" style="margin-top:10px;line-height:1.8">${state.signedIn?(state.lastBackup?'最近备份：刚刚 · 全部记录已同步':'连接网络后，自动同步文章与学习记录。'):'登录后开启跨设备同步。现在也可以导出档案，自己保存一份。'}</p></section><section class="section"><p class="small muted" style="margin-bottom:9px">备份内容</p><div class="panel white" style="padding:0 16px"><div class="form-row"><span>文章、计划与学习记录</span><span class="green">全部保留</span></div><div class="form-row"><span>同时备份录音</span>${sw(state.audioBackup,'toggle-audio-backup','同时备份录音')}</div></div><p class="small muted" style="margin-top:10px;line-height:1.8">录音默认只保存在本机。开启后占用更多空间，可以随时关闭。</p></section><section class="section"><div class="section-heading"><h2>手动保存与恢复</h2></div><div class="list">${row('file','导出完整档案','文章、计划、记录及所选录音','backup')}${row('repeat','从档案恢复','先查看内容，再合并或恢复','backup')}</div><p class="small muted" style="margin-top:10px;line-height:1.8">恢复前会保留一份当前档案。重复成绩自动去重，冲突原文保留两个版本。</p></section><section class="panel white"><h3>同步与备份各有用途</h3><p class="small muted" style="margin-top:8px;line-height:1.8">同步让设备保持一致；版本备份能找回误删。清理录音不会清除文章和成绩。</p></section></div>`+footer(state.signedIn?'立即备份':'登录开启同步',state.signedIn?'backup-demo':'go:signin');}
function signin(){return navTop('登录账户','account')+`<div class="scroll-body" style="padding-top:48px"><div class="reading-title"><span class="row-icon" style="margin:auto;width:64px;height:64px">${icon('shield')}</span><h2 style="margin-top:24px">把学习进度带到新设备</h2><p style="line-height:1.8;margin-top:14px">登录后备份文章、计划和成绩。<br>不登录，也能继续在本机背诵。</p></div><div class="checklist" style="margin:36px 8px"><div>${icon('check')}离线学习，联网后同步</div><div>${icon('check')}首次登录先确认合并档案</div><div>${icon('check')}录音是否上传，由你选择</div></div><button class="primary" data-action="login-demo">使用 Apple 登录</button><button class="text-button" data-go="account" style="margin-top:14px">暂时使用本机档案</button><p class="small muted" style="text-align:center;line-height:1.8;margin-top:30px">登录前可查看<button data-action="legal-demo" class="inline-link">服务条款</button>与<button data-action="privacy-demo" class="inline-link">隐私说明</button></p></div>`;}
const reportData={weekly:{title:'学习周报',date:'9月28日—10月4日',kicker:'这一周，稳步向前',number:'5',unit:'/ 6 个任务',caption:'本周到期任务已完成',progress:83.3,stats:[['2','节','新掌握'],['3 / 4','次','复习考核通过'],['3','次','有辅助练习'],['38','分钟','有效学习时长']],heading:'下周，先巩固这两节',rows:[['劝学 · 第3节','漏背末句 · 安排完整重考'],['师说 · 第2节','识别待确认 · 先回听核对']],foot:'复习保持率 75% · 来自4次有效复习考核。'},monthly:{title:'学习月报',date:'2026年9月',kicker:'九月目标，已经完成',number:'2',unit:'/ 2 篇文章',caption:'本月计划文章已完整通过',progress:100,stats:[['12','节','本月新掌握'],['26 / 30','个','到期任务完成'],['12 / 14','次','复习考核通过'],['186','分钟','有效学习时长']],heading:'这个月背完的文章',rows:[['劝学（节选）','6 / 6 节通过 · 最近复习9月28日'],['师说（节选）','6 / 6 节通过 · 最近复习9月30日']],foot:'复习保持率 85.7% · 来自14次有效复习考核。'},yearly:{title:'学习年报',date:'2025年',kicker:'把一小节，积累成一整年',number:'24',unit:'篇文章',caption:'全年完整通过的文章版本',progress:null,stats:[['186','节','全年新掌握'],['148','天','有学习记录'],['312 / 360','次','复习考核通过'],['42','小时','有效学习时长']],heading:'值得再读一遍',rows:[['出师表','全文通过 · 最近复习12月18日'],['赤壁赋','全文通过 · 最近复习12月23日']],foot:'复习保持率 86.7% · 来自360次有效复习考核。'}};
function report(period){const d=reportData[period];return navTop(d.title,'profile')+`<div class="scroll-body report-body" style="padding-top:16px"><nav class="segmented" aria-label="报告周期">${[['weekly','周报'],['monthly','月报'],['yearly','年报']].map(([id,label])=>`<button class="${id===period?'selected':''}" data-go="${id}">${label}</button>`).join('')}</nav><p class="small muted" style="margin:16px 0 8px">${d.date} · 已结束</p><section class="section report-hero"><p class="label blue">${d.kicker}</p><p class="summary-number numeric" style="margin-top:12px">${d.number}<small> ${d.unit}</small></p><p class="small muted" style="margin-top:7px">${d.caption}</p>${d.progress!==null?`<div class="progress"><span style="width:${d.progress}%"></span></div>`:''}</section><div class="section stat-grid">${d.stats.map(([n,u,t])=>`<div><p class="stat-number">${n}<small> ${u}</small></p><p class="small">${t}</p></div>`).join('')}</div>${period==='yearly'?`<section class="section"><div class="section-heading"><h2>每个月，都留下一点积累</h2></div><div class="month-bars" role="img" aria-label="2025年每月新掌握小节：8、12、14、16、18、12、10、16、20、24、18、18"><div class="bars">${[8,12,14,16,18,12,10,16,20,24,18,18].map((v,i)=>`<div><span class="small">${v}</span><i style="height:${v*2.5}px"></i><span>${i+1}</span></div>`).join('')}</div></div></section>`:''}<section class="section"><div class="section-heading"><h2>${d.heading}</h2></div><div class="list">${d.rows.map(([t,m])=>row(period==='weekly'?'repeat':'book',t,m,'read')).join('')}</div></section><p class="small muted" style="line-height:1.8">${d.foot}<br>自动考核、人工确认与辅助练习分别统计。</p></div>`;}
function weekly(){return report('weekly');}function monthly(){return report('monthly');}function yearly(){return report('yearly');}

function content(id){return ({today,library,import:importScreen,segments:segmentScreen,planform,planview,read,record,result,review,profile,settings,failure:()=>result(true),empty,typing,micerror,account,backup,signin,weekly,monthly,yearly}[id]||today)();}
function phone(id){return `<section class="phone" id="phone-${id}" aria-label="${screens.find(s=>s[0]===id)?.[1]||'界面'}"><div class="statusbar"><span>9:41</span><span class="status-icons">${icon('signal')}${icon('wifi')}${icon('battery','battery')}</span></div>${content(id)}<div class="home-indicator" aria-hidden="true"></div></section>`;}
const params=new URLSearchParams(location.search);
let mode=params.get('mode')||'prototype';let board=params.get('board')||'1';
if(params.has('screen')&&screens.some(s=>s[0]===params.get('screen')))state.screen=params.get('screen');
function render(){document.body.classList.toggle('gallery-page',mode==='gallery');const app=document.querySelector('#app');document.body.classList.toggle('single-page',mode==='single');if(mode==='single'){app.innerHTML=phone(state.screen);bind();return;}if(mode==='gallery'){const ids=board==='2'?screens.slice(6,12):board==='3'?screens.slice(12,16):board==='4'?screens.slice(16):screens.slice(0,6);app.innerHTML=`<header class="gallery-header"><p class="eyebrow">背诵计划 · 界面设计 / ${board==='1'?'内容与计划':board==='2'?'练习与语音校对':board==='4'?'账户与学习报告':'异常与替代路径'}</p><h1>${board==='1'?'把一篇文章，变成每天的一小节':board==='2'?'开口背诵，对照原文，达标完成': board==='4'?'保存进度，看见每一段积累':'每种状态，都有下一步'}</h1><p>${board==='1'?'导入、确认段落、设定月度目标，再把新背与复习分配到每天。':'无提示考核依据最终识别结果判定，疑点先复核，练习与自动通过分别记录。'}</p>${params.get('export')==='1'?'':`<div class="presentation-actions"><button data-mode="prototype">打开交互原型</button><button data-board="1">内容与计划</button><button data-board="2">练习与校对</button><button data-board="3">异常状态</button><button data-board="4">账户与报告</button></div>`}</header><main class="gallery-grid">${ids.map(([id,title,desc])=>`<article class="gallery-item"><div class="gallery-caption"><span>${String(screens.findIndex(s=>s[0]===id)+1).padStart(2,'0')}</span><h2>${title}</h2><p>${desc}</p></div>${phone(id)}</article>`).join('')}</main><footer class="gallery-footer">纯白简洁 · 系统 iOS 风格 · 界面为设计样例，语音与成绩为演示数据 · 2026年10月8日</footer>`;}
else if(mode==='flow'){app.innerHTML=`<header class="gallery-header"><p class="eyebrow">背诵计划 · 功能逻辑</p><h1>内容、计划、考核、复习形成闭环</h1><p>以文章与段落为核心组织；语音和文字共用校对规则；每次考核保留原始证据。</p></header><main class="flow-board"><div class="flow-steps">${[['01','内容准备','导入文章 → 确认原文 → 拆分小节<br>保留文章版本与独立段落ID'],['02','计划排期','选择文章 → 配额与截止日 → 预览<br>新背与复习分别计算'],['03','今日背诵','到期复习 → 新背 → 阅读或遮字练习<br>无提示考核新建完整会话'],['04','最终校对','结束录音 → 最终转录 → 对齐与评分<br>原文辅助识别，不补全遗漏']].map(([n,h,t])=>`<section class="flow-step"><span>${n}</span><h2>${h}</h2><p>${t}</p></section>`).join('')}</div><section class="flow-decision"><h2>评分后，进入三种明确结果</h2><div class="flow-decisions"><div><h3 class="green">达标且无疑点</h3><p>自动完成本节任务，更新掌握进度。<br>生成下次复习。全部必做任务完成才记当天打卡。</p></div><div><h3 class="orange">识别待确认</h3><p>回听对应音频，区分识别偏差与背错。<br>人工确认单独记录，建议重考获得自动通过。</p></div><div><h3 class="red">内容未达标</h3><p>标出漏句与错词，练习薄弱位置。<br>重新完整考核，不合并多次最好片段。</p></div></div></section><section class="flow-decision"><h2>底部导航与页面归属</h2><div class="flow-steps">${[['今日','新背 · 复习 · 继续任务'],['文库','文章 · 原文 · 有顺序的段落'],['计划','月度目标 · 每日配额 · 重排'],['我的','记录 · 考核规则 · 录音管理']].map(([h,t])=>`<div><h3>${h}</h3><p class="small muted" style="margin-top:10px">${t}</p></div>`).join('')}</div></section><p class="small muted" style="margin-top:24px;text-align:center">通过规则示例：一致率 ≥90% · 覆盖率 ≥95% · 关键项正确 · 无待确认疑点 · 无辅助提示</p></main>`;}
else{const[noteTitle,note]=notes[state.screen]||notes.today;app.innerHTML=`<header class="presentation-header"><div><h1>背诵计划 · 交互原型</h1><p>设计演示；语音、录音与成绩使用样例，不采集真实声音。</p></div><div class="presentation-actions"><button data-mode="gallery">查看界面图</button><button data-mode="flow">功能逻辑图</button><button data-action="reset">重置演示</button></div></header><main class="prototype-layout"><nav class="designer-nav" aria-label="设计页面"><p>页面目录 · 可点击切换</p>${screens.map(([id,title],i)=>`<button data-go="${id}" class="${state.screen===id?'active':''}"><span>${String(i+1).padStart(2,'0')}</span>${title}</button>`).join('')}</nav>${phone(state.screen)}<aside class="logic-notes"><p class="note-label">交互说明 · 不属于产品界面</p><h2>${noteTitle}</h2><p>${note}</p>${state.screen==='record'?`<div class="field" style="margin-top:22px"><label for="demo-outcome">选择演示结果</label><select id="demo-outcome"><option value="pass" ${state.recordOutcome==='pass'?'selected':''}>达标：仅漏一个字</option><option value="fail" ${state.recordOutcome==='fail'?'selected':''}>未达标：漏背整句</option><option value="uncertain" ${state.recordOutcome==='uncertain'?'selected':''}>疑点：蛟龙被识成交通</option></select></div>`:''}${state.screen==='typing'?'<button class="secondary-button" style="margin-top:20px;font-size:14px" data-action="typing-sample">填入演示样本</button>':''}<a href="../docs/功能与流程设计.md">查看完整功能与流程设计</a><a href="../docs/底座审查与开发建议.md">查看底座审查记录</a></aside></main>`;}
bind();}
function go(id){if(id==='settings')state.settingsBack=state.screen==='settings'?'profile':state.screen;if(state.screen==='record'&&!state.finalizing&&!['record','result','failure','review'].includes(id)){toast('已结束演示会话；正式产品会确认是否退出。');}state.screen=id;state.ruleDraft={accuracy:state.accuracy,coverage:state.coverage};mode='prototype';history.replaceState(null,'',`?screen=${id}`);render();window.scrollTo({top:0});}
function toast(message){document.querySelector('.toast')?.remove();const d=document.createElement('div');d.className='toast';d.setAttribute('role','status');d.textContent=message;document.body.append(d);setTimeout(()=>d.remove(),3200);}
function bind(){
 document.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.go)));
 document.querySelectorAll('[data-mode]').forEach(b=>b.addEventListener('click',()=>{mode=b.dataset.mode;board='1';history.replaceState(null,'',`?mode=${mode}`);render();}));
 document.querySelectorAll('[data-board]').forEach(b=>b.addEventListener('click',()=>{board=b.dataset.board;mode='gallery';history.replaceState(null,'',`?mode=gallery&board=${board}`);render();window.scrollTo({top:0});}));
 document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{state.filter=b.dataset.filter;render();}));
 const search=document.querySelector('#library-search');search?.addEventListener('input',e=>{state.libraryQuery=e.target.value;document.querySelector('#library-list').innerHTML=libraryRows();document.querySelectorAll('#library-list [data-go]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.go)));});
 document.querySelector('#article-title')?.addEventListener('input',e=>state.importTitle=e.target.value);
 document.querySelector('#plan-title')?.addEventListener('input',e=>state.planName=e.target.value);
 document.querySelector('#article-text')?.addEventListener('input',e=>{state.importText=e.target.value;document.querySelector('#import-count').textContent=normalize(state.importText).length+' 字';});
 document.querySelectorAll('[data-merge]').forEach(b=>b.addEventListener('click',()=>{const i=Number(b.dataset.merge);state.segments.splice(i,2,state.segments[i]+'\n'+state.segments[i+1]);render();}));
 document.querySelectorAll('[data-edit-segment]').forEach(b=>b.addEventListener('click',()=>{const i=Number(b.dataset.editSegment);const node=b.closest('.paragraph-item').querySelector('p');node.innerHTML=`<textarea aria-label="编辑第${i+1}节" style="width:100%;min-height:130px;font:inherit;line-height:1.6;border:1px solid var(--line);border-radius:10px;padding:10px">${esc(state.segments[i])}</textarea><button class="text-button">保存这一节</button>`;node.querySelector('button').addEventListener('click',()=>{const value=node.querySelector('textarea').value;if(!normalize(value)){toast('这一节不能是空白。');return;}state.segments[i]=value;render();});}));
 for(const[id,key]of[['plan-start','planStart'],['plan-end','planEnd'],['plan-quota','quota']])document.querySelector('#'+id)?.addEventListener('change',e=>{state[key]=key==='quota'?Math.min(10,Math.max(1,Number(e.target.value)||1)):e.target.value;render();});
 document.querySelectorAll('[data-weekday]').forEach(b=>b.addEventListener('click',()=>{const day=Number(b.dataset.weekday);state.weekdays=state.weekdays.includes(day)?state.weekdays.filter(d=>d!==day):[...state.weekdays,day];render();}));
 document.querySelectorAll('[data-article]').forEach(b=>b.addEventListener('change',()=>{const name=b.dataset.article;state.planArticles=b.checked?[...state.planArticles,name]:state.planArticles.filter(a=>a!==name);render();}));
 document.querySelector('#demo-outcome')?.addEventListener('change',e=>state.recordOutcome=e.target.value);
 document.querySelector('#rule-accuracy')?.addEventListener('input',e=>state.ruleDraft.accuracy=Number(e.target.value));
 document.querySelector('#rule-coverage')?.addEventListener('input',e=>state.ruleDraft.coverage=Number(e.target.value));
 document.querySelectorAll('[data-action]').forEach(b=>b.addEventListener('click',()=>act(b.dataset.action)));
}
function act(action){
 if(action==='preview-segments'){if(!state.importTitle.trim()){toast('请填写文章标题。');return;}if(!normalize(state.importText).trim()){toast('请先粘贴有效正文。');return;}state.segments=state.importText.trim().split(/\r?\n\s*\r?\n/).map(x=>x.trim()).filter(x=>normalize(x));go('segments');}
 else if(action==='clear-import'){state.importText='';render();}
 else if(action==='split-sentences'){state.segments=state.segments.flatMap(s=>s.match(/[^。！？]+[。！？]?/g)||[s]).map(s=>s.trim()).filter(Boolean);render();}
 else if(action==='save-article'){state.hasImported=true;go('library');toast(`已保存文章，共${state.segments.length}节（演示）。`);}
 else if(action==='create-plan'){const p=planPreview();if(!p.fits)return;state.planSaved=true;go('planview');toast(`排期演示：${p.n}节，预计${p.finishText}完成新背。`);}
 else if(action==='login-demo'){state.signedIn=true;go('account');toast('登录状态演示：正式产品此处先确认档案合并。');}
 else if(action==='toggle-audio-backup'){state.audioBackup=!state.audioBackup;render();}
 else if(action==='backup-demo'){state.lastBackup=true;render();toast('备份状态演示；没有上传任何数据。');}
 else if(action==='legal-demo'||action==='privacy-demo'){toast('正式产品此处展示条款全文；原型不提交登录。');}
 else if(action==='toggle-mask'){state.mask=!state.mask;render();}
 else if(action==='toggle-size'){state.large=!state.large;render();}
 else if(action==='start-record'){state.assisted=false;state.transcript=false;state.paused=false;state.finalizing=false;state.reviewDecision=null;go('record');}
 else if(action==='pause'){state.paused=!state.paused;render();}
 else if(action==='toggle-transcript'){state.transcript=!state.transcript;if(state.transcript)state.assisted=true;render();}
 else if(action==='finish-record'){if(state.finalizing)return;state.finalizing=true;render();document.querySelector('[data-action="finish-record"]').disabled=true;setTimeout(()=>{state.finalizing=false;if(state.recordOutcome==='uncertain')go('review');else{state.lastResult=state.recordOutcome;const s=align(target,fixtures[state.recordOutcome]);if(state.recordOutcome==='pass'&&!state.assisted&&s.accuracy>=state.accuracy&&s.coverage>=state.coverage)state.taskDone=true;go(state.recordOutcome==='fail'?'failure':'result');}},750);}
 else if(action==='complete-demo'){state.taskDone=true;go('today');toast('这一节已完成；今日还有1节复习任务。');}
 else if(action==='review-asr'){state.reviewDecision='asr';render();}
 else if(action==='review-wrong'){state.reviewDecision='wrong';render();}
 else if(action==='save-rules'){const{accuracy,coverage}=state.ruleDraft;if(!Number.isFinite(accuracy)||!Number.isFinite(coverage)||accuracy<50||accuracy>100||coverage<50||coverage>100){toast('阈值请填写50至100之间的数值。');return;}state.accuracy=accuracy;state.coverage=coverage;go(state.settingsBack);toast('规则已保存，将用于后续演示考核。');}
 else if(action==='typing-sample'){document.querySelector('#typed-answer').value=fixtures.pass;}
 else if(action==='submit-typing'){const typed=document.querySelector('#typed-answer').value;if(!normalize(typed).trim()){toast('请先输入背诵内容。');return;}const s=align(target,typed);toast(`演示校对：一致率${s.accuracy.toFixed(1)}%，覆盖率${s.coverage.toFixed(1)}%。`);}
 else if(action==='reset'){location.href='index.html';}
 else if(action==='replan'){go('planform');toast('正式产品会先预览剩余任务，历史记录保持不变。');}
 else if(action==='export-demo'){const blob=new Blob([JSON.stringify({说明:'设计演示数据，不是真实成绩',规则:{一致率:state.accuracy,覆盖率:state.coverage},样例原文:target},null,2)],{type:'application/json;charset=utf-8'});const a=document.createElement('a');const u=URL.createObjectURL(blob);a.href=u;a.download='背诵计划-演示数据.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
 else{const messages={'file-demo':'原型不读取文件。正式首版接入TXT/CSV导入。','read-aloud':'原型不播放答案。正式产品使用系统朗读。','play-demo':'原型没有真实录音。正式产品回听对应音频。','audio-settings':'设计默认本地保存录音7天，可关闭或调整。','system-settings':'原型不能跳转系统设置，可切换文字考核。','key-rule':'首版关键项规则固定开启；可在文章中选择关键项。','normalization-rule':'评分忽略标点与空白，保留原始文本。','homophone-rule':'同音容错必须有语音证据支持。','review-rule':'低置信疑点未解决时，不自动通过。'};toast(messages[action]||'该操作已列入功能设计。');}
}
render();
// 暴露纯函数用于本地有意义的验证；不访问真实语音服务。
window.PrototypeLogic={normalize,align,planPreview,state,fixtures,target};
